export interface FAQItem {
  question: string;
  answer: string;
}

export const faqData: FAQItem[] = [
  {
    question: "AM I GUARANTEED TO RANK UP?",
    answer: "ACHIEVING A HIGHER RANK DEPENDS ON YOUR COMMITMENT. IF YOU IMPLEMENT OUR FEEDBACK, PUT IN THE EFFORT, AND TAKE RESPONSIBILITY FOR YOUR PROGRESS, YOU WILL RANK UP. IT'S AKIN TO ASKING A GYM FOR A GUARANTEE ON A 6-PACK. SHOW UP, FOLLOW THE GUIDANCE, AND TRAIN HARD FOR VISIBLE RESULTS."
  },
  {
    question: "I'M IN X COUNTRY, CAN I JOIN?",
    answer: "OF COURSE! RANK UP ACADEMY IS ACCESSIBLE TO ANYONE WORLDWIDE. WHILE CLASSES ARE CONDUCTED IN REAL-TIME, ALL SESSIONS ARE RECORDED, ALLOWING YOU TO WATCH AT YOUR CONVENIENCE."
  },
  {
    question: "IS IT SUITABLE FOR X RANK?",
    answer: "YES. RANK UP ACADEMY CATERS TO PLAYERS ACROSS ALL RANKS, FROM BRONZE 5 TO TOP 500. OUR TEACHINGS ARE FOCUSED ON FUNDAMENTALS COMBINED WITH CUSTOMIZED FEEDBACK FOR EACH INDIVIDUAL, ENSURING MAXIMUM PROGRESS FOR EVERYONE."
  },
  {
    question: "I'M ON CONSOLE, CAN I JOIN?",
    answer: "ABSOLUTELY. ALL PLATFORMS ARE WELCOME AT RANK UP ACADEMY."
  },
  {
    question: "I DON'T HAVE TIME, IS IT WORTH IT?",
    answer: "DEFINITELY. RANK UP ACADEMY MAXIMIZES THE VALUE YOU GET FROM EVERY HOUR INVESTED. QUALITY IMPROVEMENT WITH LIMITED TIME IS FAR BETTER THAN MINDLESSLY GRINDING WITH AN EXCESS OF TIME."
  },
  {
    question: "I PLAY X HERO, CAN YOU TEACH ME?",
    answer: "WITHOUT A DOUBT. RANK UP ACADEMY COVERS SIMPLE AND PRACTICAL FUNDAMENTALS FOR EVERY HERO."
  }
];